# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa17ae0d28f7ede9ce74b4e24d174b248e5a4f8757efab671ae6f9f1016e784494948511ebe4de3a8d1b4e96a96f97c2ad17456f76bc2a40026c8fdf34c1a9ec

test:
  secret_key_base: 4b4cb9a68d5b34d75e1310e65800fced569d1cdec1df05cacdd4e7ca37c8b56456a73538001565c97e81de89f11f8992c855b5ce566d8f3d26728dcfa2dab898

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
